title: My Personal Website
description: This is my awesome GitHub Pages website.
baseurl: "" # Leave it empty for your main GitHub Pages site.
url: "https://username.github.io" # Replace with your GitHub Pages URL
theme: minima # Or whatever theme you're using